# Generated by Django 3.0.3 on 2020-05-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_DOB', models.DateField()),
                ('patient_address', models.CharField(max_length=50)),
                ('patient_current_medicine', models.CharField(max_length=50)),
            ],
        ),
    ]
