# Generated by Django 3.0.3 on 2020-06-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_name', models.CharField(default=None, max_length=50)),
                ('medical_address', models.CharField(default=None, max_length=50)),
                ('medical_timing', models.CharField(default=None, max_length=50)),
                ('medical_phone', models.CharField(default=None, max_length=50)),
                ('medical_medicine', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(default=None, max_length=50)),
                ('medicine_drug_content', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_DOB',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_address',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_current_medicine',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
