# Generated by Django 3.0.3 on 2020-06-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20200611_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='medicines',
            field=models.ManyToManyField(to='patient.medicine'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='patients',
            field=models.ManyToManyField(to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='medical_address',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='medical',
            name='medical_medicine',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='medical',
            name='medical_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='medical',
            name='medical_phone',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='medical',
            name='medical_timing',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_drug_content',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_address',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_current_medicine',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
