# Generated by Django 3.0.3 on 2020-06-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20200611_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical',
            name='medical_medicine',
        ),
    ]
