# Generated by Django 3.0.3 on 2020-06-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_medical_medical_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='patients',
        ),
        migrations.AddField(
            model_name='patient',
            name='medicines',
            field=models.ManyToManyField(to='patient.medicine'),
        ),
    ]
